# pull official base image
FROM node:14.5-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./

# add app
COPY . ./

RUN npm install && npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
