version: '3.7'

services:
  frontend:
    container_name: planning-poker-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    container_name: planning-poker-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - "5000:5000"
      - "5005:5005"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
    
  redis:
    image: redis:alpine
  