version: '3.7'

services:
  frontend:
    container_name: planning-poker-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true    
    depends_on:
      - backend
